// <auto-generated />
using HotelListingV2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelListingV2.Migrations
{
    [DbContext(typeof(HotelListingDbContext))]
    [Migration("20230215081749_DefaultValues")]
    partial class DefaultValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelListingV2.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Srbija",
                            ShortName = "Srb"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mauricijus",
                            ShortName = "Mau"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Germany",
                            ShortName = "Ger"
                        });
                });

            modelBuilder.Entity("HotelListingV2.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Markov Hotel",
                            Rating = 10.0
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 2,
                            Name = "Marijin Hotel",
                            Rating = 9.9000000000000004
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 3,
                            Name = "Milanov Hotel",
                            Rating = 6.0
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "Milicin Hotle",
                            Rating = 6.7999999999999998
                        });
                });

            modelBuilder.Entity("HotelListingV2.Data.Hotel", b =>
                {
                    b.HasOne("HotelListingV2.Data.Country", null)
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelListingV2.Data.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
